# =========================
#   GENERAL INFORMATIONS
# =========================

name: Souls
main: Minestrap\Souls\Main
api: [4.0.0]
version: 1.0.1

# =========================
#    OTHER INFORMATIONS
# =========================

author: ["HenryDM"]
website: "https://minestrap.github.io/"
description: "A plugin to add souls to players in your server"

softdepend: ["EconomyAPI", "BedrockEconomy"]

# =========================
#        PERMISSIONS
# =========================

permissions: 
  souls.sell.command:
    description: "default souls sell command permission"
    default: true

  souls.view.command:
    description: "default souls view command permission"
    default: true
